!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!  This file is AUTOMATICALLY GENERATED by:
!!  tools/fortran_wrappers.pl include/magmablas_z.i
!!  Do not edit.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

module magmablas_zfortran

use magma_param

implicit none

!---- Fortran interfaces to MAGMA subroutines ----
interface

subroutine magmablasf_ztranspose_inplace( n, dA, ldda, queue )
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: queue
end

subroutine magmablasf_ztranspose_conj_inplace( n, dA, ldda, queue )
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: queue
end

subroutine magmablasf_ztranspose( m, n, dA, ldda, dAT, lddat, queue )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dAT
    integer          :: lddat
    magma_devptr_t   :: queue
end

subroutine magmablasf_ztranspose_conj( m, n, dA, ldda, dAT, lddat, queue )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dAT
    integer          :: lddat
    magma_devptr_t   :: queue
end

subroutine magmablasf_zgetmatrix_transpose( m, n, nb, dAT, ldda, hA, lda, dwork, lddw,  &
        queues )
    integer          :: m
    integer          :: n
    integer          :: nb
    magma_devptr_t   :: dAT
    integer          :: ldda
    complex*16       :: hA(*)
    integer          :: lda
    magma_devptr_t   :: dwork
    integer          :: lddw
    magma_devptr_t   :: queues(*)
end

subroutine magmablasf_zsetmatrix_transpose( m, n, nb, hA, lda, dAT, ldda, dwork, lddw,  &
        queues )
    integer          :: m
    integer          :: n
    integer          :: nb
    complex*16       :: hA(*)
    integer          :: lda
    magma_devptr_t   :: dAT
    integer          :: ldda
    magma_devptr_t   :: dwork
    integer          :: lddw
    magma_devptr_t   :: queues(*)
end

subroutine magmablasf_zprbt( n, dA, ldda, du, dv, queue )
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: du
    magma_devptr_t   :: dv
    magma_devptr_t   :: queue
end

subroutine magmablasf_zprbt_mv( n, dv, db, queue )
    integer          :: n
    magma_devptr_t   :: dv
    magma_devptr_t   :: db
    magma_devptr_t   :: queue
end

subroutine magmablasf_zprbt_mtv( n, du, db, queue )
    integer          :: n
    magma_devptr_t   :: du
    magma_devptr_t   :: db
    magma_devptr_t   :: queue
end

subroutine magmablasf_zgeadd( m, n, alpha, dA, ldda, dB, lddb, queue )
    integer          :: m
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    magma_devptr_t   :: queue
end

subroutine magmablasf_zgeadd2( m, n, alpha, dA, ldda, beta, dB, lddb, queue )
    integer          :: m
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    complex*16       :: beta
    magma_devptr_t   :: dB
    integer          :: lddb
    magma_devptr_t   :: queue
end

subroutine magmablasf_zlacpy( uplo, m, n, dA, ldda, dB, lddb, queue )
    character        :: uplo
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    magma_devptr_t   :: queue
end

subroutine magmablasf_zlacpy_conj( n, dA1, lda1, dA2, lda2, queue )
    integer          :: n
    magma_devptr_t   :: dA1
    integer          :: lda1
    magma_devptr_t   :: dA2
    integer          :: lda2
    magma_devptr_t   :: queue
end

subroutine magmablasf_zlacpy_sym_in( uplo, m, n, rows, perm, dA, ldda, dB, lddb, queue )
    character        :: uplo
    integer          :: m
    integer          :: n
    integer          :: rows(*)
    integer          :: perm(*)
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    magma_devptr_t   :: queue
end

subroutine magmablasf_zlacpy_sym_out( uplo, m, n, rows, perm, dA, ldda, dB, lddb, queue )
    character        :: uplo
    integer          :: m
    integer          :: n
    integer          :: rows(*)
    integer          :: perm(*)
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    magma_devptr_t   :: queue
end

double precision function magmablasf_zlange( norm, m, n, dA, ldda, dwork, lwork, queue )
    character        :: norm
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dwork
    integer          :: lwork
    magma_devptr_t   :: queue
end

double precision function magmablasf_zlanhe( norm, uplo, n, dA, ldda, dwork, lwork, queue  &
        )
    character        :: norm
    character        :: uplo
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dwork
    integer          :: lwork
    magma_devptr_t   :: queue
end

subroutine magmablasf_zlascl( type, kl, ku, cfrom, cto, m, n, dA, ldda, queue, info )
    character        :: type
    integer          :: kl
    integer          :: ku
    double precision :: cfrom
    double precision :: cto
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: queue
    integer          :: info
end

subroutine magmablasf_zlascl_2x2( type, m, dW, lddw, dA, ldda, queue, info )
    character        :: type
    integer          :: m
    magma_devptr_t   :: dW
    integer          :: lddw
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: queue
    integer          :: info
end

subroutine magmablasf_zlascl2( type, m, n, dD, dA, ldda, queue, info )
    character        :: type
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dD
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: queue
    integer          :: info
end

subroutine magmablasf_zlascl_diag( type, m, n, dD, lddd, dA, ldda, queue, info )
    character        :: type
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dD
    integer          :: lddd
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: queue
    integer          :: info
end

subroutine magmablasf_zlaset( uplo, m, n, offdiag, diag, dA, ldda, queue )
    character        :: uplo
    integer          :: m
    integer          :: n
    complex*16       :: offdiag
    complex*16       :: diag
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: queue
end

subroutine magmablasf_zlaset_band( uplo, m, n, k, offdiag, diag, dA, ldda, queue )
    character        :: uplo
    integer          :: m
    integer          :: n
    integer          :: k
    complex*16       :: offdiag
    complex*16       :: diag
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: queue
end

subroutine magmablasf_zlaswp( n, dAT, ldda, k1, k2, ipiv, inci, queue )
    integer          :: n
    magma_devptr_t   :: dAT
    integer          :: ldda
    integer          :: k1
    integer          :: k2
    integer          :: ipiv(*)
    integer          :: inci
    magma_devptr_t   :: queue
end

subroutine magmablasf_zlaswp2( n, dAT, ldda, k1, k2, d_ipiv, inci, queue )
    integer          :: n
    magma_devptr_t   :: dAT
    integer          :: ldda
    integer          :: k1
    integer          :: k2
    magma_devptr_t   :: d_ipiv
    integer          :: inci
    magma_devptr_t   :: queue
end

subroutine magmablasf_zlaswp_sym( n, dA, ldda, k1, k2, ipiv, inci, queue )
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: k1
    integer          :: k2
    integer          :: ipiv(*)
    integer          :: inci
    magma_devptr_t   :: queue
end

subroutine magmablasf_zlaswpx( n, dA, ldx, ldy, k1, k2, ipiv, inci, queue )
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldx
    integer          :: ldy
    integer          :: k1
    integer          :: k2
    integer          :: ipiv(*)
    integer          :: inci
    magma_devptr_t   :: queue
end

subroutine magmablasf_zsymmetrize( uplo, m, dA, ldda, queue )
    character        :: uplo
    integer          :: m
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: queue
end

subroutine magmablasf_zsymmetrize_tiles( uplo, m, dA, ldda, ntile, mstride, nstride,  &
        queue )
    character        :: uplo
    integer          :: m
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: ntile
    integer          :: mstride
    integer          :: nstride
    magma_devptr_t   :: queue
end

subroutine magmablasf_ztrtri_diag( uplo, diag, n, dA, ldda, d_dinvA, queue )
    character        :: uplo
    character        :: diag
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: d_dinvA
    magma_devptr_t   :: queue
end

integer function magmaf_zlarfb_gpu( side, trans, direct, storev, m, n, k, dV, lddv, dT,  &
        lddt, dC, lddc, dwork, ldwork, queue )
    character        :: side
    character        :: trans
    character        :: direct
    character        :: storev
    integer          :: m
    integer          :: n
    integer          :: k
    magma_devptr_t   :: dV
    integer          :: lddv
    magma_devptr_t   :: dT
    integer          :: lddt
    magma_devptr_t   :: dC
    integer          :: lddc
    magma_devptr_t   :: dwork
    integer          :: ldwork
    magma_devptr_t   :: queue
end

integer function magmaf_zlarfb_gpu_gemm( side, trans, direct, storev, m, n, k, dV, lddv,  &
        dT, lddt, dC, lddc, dwork, ldwork, dworkvt, ldworkvt, queue )
    character        :: side
    character        :: trans
    character        :: direct
    character        :: storev
    integer          :: m
    integer          :: n
    integer          :: k
    magma_devptr_t   :: dV
    integer          :: lddv
    magma_devptr_t   :: dT
    integer          :: lddt
    magma_devptr_t   :: dC
    integer          :: lddc
    magma_devptr_t   :: dwork
    integer          :: ldwork
    magma_devptr_t   :: dworkvt
    integer          :: ldworkvt
    magma_devptr_t   :: queue
end

subroutine magmaf_zlarfbx_gpu( m, k, V, ldv, dT, ldt, c, dwork, queue )
    integer          :: m
    integer          :: k
    magma_devptr_t   :: V
    integer          :: ldv
    magma_devptr_t   :: dT
    integer          :: ldt
    magma_devptr_t   :: c
    magma_devptr_t   :: dwork
    magma_devptr_t   :: queue
end

subroutine magmaf_zlarfgtx_gpu( n, dx0, dx, dtau, dxnorm, dA, iter, V, ldv, T, ldt,  &
        dwork, queue )
    integer          :: n
    magma_devptr_t   :: dx0
    magma_devptr_t   :: dx
    magma_devptr_t   :: dtau
    magma_devptr_t   :: dxnorm
    magma_devptr_t   :: dA
    integer          :: iter
    magma_devptr_t   :: V
    integer          :: ldv
    magma_devptr_t   :: T
    integer          :: ldt
    magma_devptr_t   :: dwork
    magma_devptr_t   :: queue
end

subroutine magmaf_zlarfgx_gpu( n, dx0, dx, dtau, dxnorm, dA, iter, queue )
    integer          :: n
    magma_devptr_t   :: dx0
    magma_devptr_t   :: dx
    magma_devptr_t   :: dtau
    magma_devptr_t   :: dxnorm
    magma_devptr_t   :: dA
    integer          :: iter
    magma_devptr_t   :: queue
end

subroutine magmaf_zlarfx_gpu( m, n, v, tau, C, ldc, xnorm, dT, iter, work, queue )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: v
    magma_devptr_t   :: tau
    magma_devptr_t   :: C
    integer          :: ldc
    magma_devptr_t   :: xnorm
    magma_devptr_t   :: dT
    integer          :: iter
    magma_devptr_t   :: work
    magma_devptr_t   :: queue
end

subroutine magmablasf_zaxpycp( m, dr, dx, db, queue )
    integer          :: m
    magma_devptr_t   :: dr
    magma_devptr_t   :: dx
    magma_devptr_t   :: db
    magma_devptr_t   :: queue
end

subroutine magmablasf_zswap( n, dx, incx, dy, incy, queue )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: queue
end

subroutine magmablasf_zswapblk( order, n, dA, ldda, dB, lddb, i1, i2, ipiv, inci, offset,  &
        queue )
    character        :: order
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    integer          :: i1
    integer          :: i2
    integer          :: ipiv(*)
    integer          :: inci
    integer          :: offset
    magma_devptr_t   :: queue
end

subroutine magmablasf_zswapdblk( n, nb, dA, ldda, inca, dB, lddb, incb, queue )
    integer          :: n
    integer          :: nb
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: inca
    magma_devptr_t   :: dB
    integer          :: lddb
    integer          :: incb
    magma_devptr_t   :: queue
end

subroutine magmablasf_dznrm2_adjust( k, dxnorm, dc, queue )
    integer          :: k
    magma_devptr_t   :: dxnorm
    magma_devptr_t   :: dc
    magma_devptr_t   :: queue
end

subroutine magmablasf_dznrm2_check( m, n, dA, ldda, dxnorm, dlsticc, queue )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dxnorm
    magma_devptr_t   :: dlsticc
    magma_devptr_t   :: queue
end

subroutine magmablasf_dznrm2_cols( m, n, dA, ldda, dxnorm, queue )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dxnorm
    magma_devptr_t   :: queue
end

subroutine magmablasf_dznrm2_row_check_adjust( k, tol, dxnorm, dxnorm2, dC, lddc,  &
        dlsticc, queue )
    integer          :: k
    double precision :: tol
    magma_devptr_t   :: dxnorm
    magma_devptr_t   :: dxnorm2
    magma_devptr_t   :: dC
    integer          :: lddc
    magma_devptr_t   :: dlsticc
    magma_devptr_t   :: queue
end

subroutine magmablasf_ztrsv( uplo, transA, diag, n, dA, ldda, db, incb, queue )
    character        :: uplo
    character        :: transA
    character        :: diag
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: db
    integer          :: incb
    magma_devptr_t   :: queue
end

subroutine magmablasf_ztrsv_outofplace( uplo, transA, diag, n, dA, ldda, db, incb, dx,  &
        queue, flag )
    character        :: uplo
    character        :: transA
    character        :: diag
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: db
    integer          :: incb
    magma_devptr_t   :: dx
    magma_devptr_t   :: queue
    integer          :: flag
end

subroutine magmablasf_zgemv( trans, m, n, alpha, dA, ldda, dx, incx, beta, dy, incy,  &
        queue )
    character        :: trans
    integer          :: m
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    complex*16       :: beta
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: queue
end

subroutine magmablasf_zgemv_conj( m, n, alpha, dA, ldda, dx, incx, beta, dy, incy, queue  &
        )
    integer          :: m
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    complex*16       :: beta
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: queue
end

integer function magmablasf_zhemv( uplo, n, alpha, dA, ldda, dx, incx, beta, dy, incy,  &
        queue )
    character        :: uplo
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    complex*16       :: beta
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: queue
end

integer function magmablasf_zsymv( uplo, n, alpha, dA, ldda, dx, incx, beta, dy, incy,  &
        queue )
    character        :: uplo
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    complex*16       :: beta
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: queue
end

integer function magmablasf_zhemv_work( uplo, n, alpha, dA, ldda, dx, incx, beta, dy,  &
        incy, dwork, lwork, queue )
    character        :: uplo
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    complex*16       :: beta
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: dwork
    integer          :: lwork
    magma_devptr_t   :: queue
end

integer function magmablasf_zsymv_work( uplo, n, alpha, dA, ldda, dx, incx, beta, dy,  &
        incy, dwork, lwork, queue )
    character        :: uplo
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    complex*16       :: beta
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: dwork
    integer          :: lwork
    magma_devptr_t   :: queue
end

subroutine magmablasf_zgemm( transA, transB, m, n, k, alpha, dA, ldda, dB, lddb, beta,  &
        dC, lddc, queue )
    character        :: transA
    character        :: transB
    integer          :: m
    integer          :: n
    integer          :: k
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    complex*16       :: beta
    magma_devptr_t   :: dC
    integer          :: lddc
    magma_devptr_t   :: queue
end

subroutine magmablasf_zgemm_reduce( m, n, k, alpha, dA, ldda, dB, lddb, beta, dC, lddc,  &
        queue )
    integer          :: m
    integer          :: n
    integer          :: k
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    complex*16       :: beta
    magma_devptr_t   :: dC
    integer          :: lddc
    magma_devptr_t   :: queue
end

subroutine magmablasf_ztrsm( side, uplo, transA, diag, m, n, alpha, dA, ldda, dB, lddb,  &
        queue )
    character        :: side
    character        :: uplo
    character        :: transA
    character        :: diag
    integer          :: m
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    magma_devptr_t   :: queue
end

subroutine magmablasf_ztrsm_outofplace( side, uplo, transA, diag, m, n, alpha, dA, ldda,  &
        dB, lddb, dX, lddx, flag, d_dinvA, dinvA_length, queue )
    character        :: side
    character        :: uplo
    character        :: transA
    character        :: diag
    integer          :: m
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    magma_devptr_t   :: dX
    integer          :: lddx
    integer          :: flag
    magma_devptr_t   :: d_dinvA
    integer          :: dinvA_length
    magma_devptr_t   :: queue
end

subroutine magmablasf_ztrsm_work( side, uplo, transA, diag, m, n, alpha, dA, ldda, dB,  &
        lddb, dX, lddx, flag, d_dinvA, dinvA_length, queue )
    character        :: side
    character        :: uplo
    character        :: transA
    character        :: diag
    integer          :: m
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    magma_devptr_t   :: dX
    integer          :: lddx
    integer          :: flag
    magma_devptr_t   :: d_dinvA
    integer          :: dinvA_length
    magma_devptr_t   :: queue
end

subroutine magmaf_zsetvector( n, hx_src, incx, dy_dst, incy, queue )
    integer          :: n
    complex*16       :: hx_src(*)
    integer          :: incx
    magma_devptr_t   :: dy_dst
    integer          :: incy
    magma_devptr_t   :: queue
end

subroutine magmaf_zgetvector( n, dx_src, incx, hy_dst, incy, queue )
    integer          :: n
    magma_devptr_t   :: dx_src
    integer          :: incx
    complex*16       :: hy_dst(*)
    integer          :: incy
    magma_devptr_t   :: queue
end

subroutine magmaf_zcopyvector( n, dx_src, incx, dy_dst, incy, queue )
    integer          :: n
    magma_devptr_t   :: dx_src
    integer          :: incx
    magma_devptr_t   :: dy_dst
    integer          :: incy
    magma_devptr_t   :: queue
end

subroutine magmaf_zsetvector_async( n, hx_src, incx, dy_dst, incy, queue )
    integer          :: n
    complex*16       :: hx_src(*)
    integer          :: incx
    magma_devptr_t   :: dy_dst
    integer          :: incy
    magma_devptr_t   :: queue
end

subroutine magmaf_zgetvector_async( n, dx_src, incx, hy_dst, incy, queue )
    integer          :: n
    magma_devptr_t   :: dx_src
    integer          :: incx
    complex*16       :: hy_dst(*)
    integer          :: incy
    magma_devptr_t   :: queue
end

subroutine magmaf_zcopyvector_async( n, dx_src, incx, dy_dst, incy, queue )
    integer          :: n
    magma_devptr_t   :: dx_src
    integer          :: incx
    magma_devptr_t   :: dy_dst
    integer          :: incy
    magma_devptr_t   :: queue
end

subroutine magmaf_zsetmatrix( m, n, hA_src, lda, dB_dst, lddb, queue )
    integer          :: m
    integer          :: n
    complex*16       :: hA_src(*)
    integer          :: lda
    magma_devptr_t   :: dB_dst
    integer          :: lddb
    magma_devptr_t   :: queue
end

subroutine magmaf_zgetmatrix( m, n, dA_src, ldda, hB_dst, ldb, queue )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA_src
    integer          :: ldda
    complex*16       :: hB_dst(*)
    integer          :: ldb
    magma_devptr_t   :: queue
end

subroutine magmaf_zcopymatrix( m, n, dA_src, ldda, dB_dst, lddb, queue )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA_src
    integer          :: ldda
    magma_devptr_t   :: dB_dst
    integer          :: lddb
    magma_devptr_t   :: queue
end

subroutine magmaf_zsetmatrix_async( m, n, hA_src, lda, dB_dst, lddb, queue )
    integer          :: m
    integer          :: n
    complex*16       :: hA_src(*)
    integer          :: lda
    magma_devptr_t   :: dB_dst
    integer          :: lddb
    magma_devptr_t   :: queue
end

subroutine magmaf_zgetmatrix_async( m, n, dA_src, ldda, hB_dst, ldb, queue )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA_src
    integer          :: ldda
    complex*16       :: hB_dst(*)
    integer          :: ldb
    magma_devptr_t   :: queue
end

subroutine magmaf_zcopymatrix_async( m, n, dA_src, ldda, dB_dst, lddb, queue )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA_src
    integer          :: ldda
    magma_devptr_t   :: dB_dst
    integer          :: lddb
    magma_devptr_t   :: queue
end

integer function magmaf_izamax( n, dx, incx, queue )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: queue
end

integer function magmaf_izamin( n, dx, incx, queue )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: queue
end

double precision function magmaf_dzasum( n, dx, incx, queue )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: queue
end

subroutine magmaf_zaxpy( n, alpha, dx, incx, dy, incy, queue )
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: queue
end

subroutine magmaf_zcopy( n, dx, incx, dy, incy, queue )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: queue
end

double precision function magmaf_dznrm2( n, dx, incx, queue )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: queue
end

subroutine magmaf_zrot( n, dx, incx, dy, incy, dc, ds, queue )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
    double precision :: dc
    complex*16       :: ds
    magma_devptr_t   :: queue
end

subroutine magmaf_zdrot( n, dx, incx, dy, incy, dc, ds, queue )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
    double precision :: dc
    double precision :: ds
    magma_devptr_t   :: queue
end

subroutine magmaf_zrotg( a, b, c, s, queue )
    magma_devptr_t   :: a
    magma_devptr_t   :: b
    magma_devptr_t   :: c
    magma_devptr_t   :: s
    magma_devptr_t   :: queue
end

subroutine magmaf_zscal( n, alpha, dx, incx, queue )
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: queue
end

subroutine magmaf_zdscal( n, alpha, dx, incx, queue )
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: queue
end

subroutine magmaf_zswap( n, dx, incx, dy, incy, queue )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: queue
end

subroutine magmaf_zgemv( transA, m, n, alpha, dA, ldda, dx, incx, beta, dy, incy, queue )
    character        :: transA
    integer          :: m
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    complex*16       :: beta
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: queue
end

subroutine magmaf_zgerc( m, n, alpha, dx, incx, dy, incy, dA, ldda, queue )
    integer          :: m
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: queue
end

subroutine magmaf_zgeru( m, n, alpha, dx, incx, dy, incy, dA, ldda, queue )
    integer          :: m
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: queue
end

subroutine magmaf_zhemv( uplo, n, alpha, dA, ldda, dx, incx, beta, dy, incy, queue )
    character        :: uplo
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    complex*16       :: beta
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: queue
end

subroutine magmaf_zher( uplo, n, alpha, dx, incx, dA, ldda, queue )
    character        :: uplo
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: queue
end

subroutine magmaf_zher2( uplo, n, alpha, dx, incx, dy, incy, dA, ldda, queue )
    character        :: uplo
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: queue
end

subroutine magmaf_zsymv( uplo, n, alpha, dA, ldda, dx, incx, beta, dy, incy, queue )
    character        :: uplo
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    complex*16       :: beta
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: queue
end

subroutine magmaf_zsyr( uplo, n, alpha, dx, incx, dA, ldda, queue )
    character        :: uplo
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: queue
end

subroutine magmaf_zsyr2( uplo, n, alpha, dx, incx, dy, incy, dA, ldda, queue )
    character        :: uplo
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: queue
end

subroutine magmaf_ztrmv( uplo, trans, diag, n, dA, ldda, dx, incx, queue )
    character        :: uplo
    character        :: trans
    character        :: diag
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: queue
end

subroutine magmaf_ztrsv( uplo, trans, diag, n, dA, ldda, dx, incx, queue )
    character        :: uplo
    character        :: trans
    character        :: diag
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: queue
end

subroutine magmaf_zgemm( transA, transB, m, n, k, alpha, dA, ldda, dB, lddb, beta, dC,  &
        lddc, queue )
    character        :: transA
    character        :: transB
    integer          :: m
    integer          :: n
    integer          :: k
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    complex*16       :: beta
    magma_devptr_t   :: dC
    integer          :: lddc
    magma_devptr_t   :: queue
end

subroutine magmaf_zhemm( side, uplo, m, n, alpha, dA, ldda, dB, lddb, beta, dC, lddc,  &
        queue )
    character        :: side
    character        :: uplo
    integer          :: m
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    complex*16       :: beta
    magma_devptr_t   :: dC
    integer          :: lddc
    magma_devptr_t   :: queue
end

subroutine magmaf_zher2k( uplo, trans, n, k, alpha, dA, ldda, dB, lddb, beta, dC, lddc,  &
        queue )
    character        :: uplo
    character        :: trans
    integer          :: n
    integer          :: k
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    double precision :: beta
    magma_devptr_t   :: dC
    integer          :: lddc
    magma_devptr_t   :: queue
end

subroutine magmaf_zherk( uplo, trans, n, k, alpha, dA, ldda, beta, dC, lddc, queue )
    character        :: uplo
    character        :: trans
    integer          :: n
    integer          :: k
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    double precision :: beta
    magma_devptr_t   :: dC
    integer          :: lddc
    magma_devptr_t   :: queue
end

subroutine magmaf_zsymm( side, uplo, m, n, alpha, dA, ldda, dB, lddb, beta, dC, lddc,  &
        queue )
    character        :: side
    character        :: uplo
    integer          :: m
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    complex*16       :: beta
    magma_devptr_t   :: dC
    integer          :: lddc
    magma_devptr_t   :: queue
end

subroutine magmaf_zsyr2k( uplo, trans, n, k, alpha, dA, ldda, dB, lddb, beta, dC, lddc,  &
        queue )
    character        :: uplo
    character        :: trans
    integer          :: n
    integer          :: k
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    complex*16       :: beta
    magma_devptr_t   :: dC
    integer          :: lddc
    magma_devptr_t   :: queue
end

subroutine magmaf_zsyrk( uplo, trans, n, k, alpha, dA, ldda, beta, dC, lddc, queue )
    character        :: uplo
    character        :: trans
    integer          :: n
    integer          :: k
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    complex*16       :: beta
    magma_devptr_t   :: dC
    integer          :: lddc
    magma_devptr_t   :: queue
end

subroutine magmaf_ztrmm( side, uplo, trans, diag, m, n, alpha, dA, ldda, dB, lddb, queue  &
        )
    character        :: side
    character        :: uplo
    character        :: trans
    character        :: diag
    integer          :: m
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    magma_devptr_t   :: queue
end

subroutine magmaf_ztrsm( side, uplo, trans, diag, m, n, alpha, dA, ldda, dB, lddb, queue  &
        )
    character        :: side
    character        :: uplo
    character        :: trans
    character        :: diag
    integer          :: m
    integer          :: n
    complex*16       :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    magma_devptr_t   :: queue
end

integer function magmaf_zpotf2_lpout( uplo, n, dA, lda, gbstep, dinfo, queue )
    character        :: uplo
    integer          :: n
    complex*16       :: dA(*)
    integer          :: lda
    integer          :: gbstep
    integer          :: dinfo(*)
    magma_devptr_t   :: queue
end

integer function magmaf_zpotf2_lpin( uplo, n, dA, lda, gbstep, dinfo, queue )
    character        :: uplo
    integer          :: n
    complex*16       :: dA(*)
    integer          :: lda
    integer          :: gbstep
    integer          :: dinfo(*)
    magma_devptr_t   :: queue
end

end interface

end module magmablas_zfortran
